import Head from "next/head";
import Image from "next/image";

import styles from '@/styles/Home.module.css'
import heroImg from '@/public/assets/hero.png'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Meu project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="styles logoContent">
          <div className={styles.imageContainer}>
            <Image
              className={styles.hero}
              alt="Logo Tarefas"
              src={heroImg}
              priority
            />
          </div>
          <h1 className={styles.title}>
            Sistema feito para você organizar <br></br>
            seus estudos
          </h1>

          <div className={styles.infoContent}>
            <section className={styles.box}>
              <span>+12 posts</span>
            </section>
            <section className={styles.box}>
              <span>+90 comentários</span>
            </section>
          </div>

        </div>
      </main>
    </div>
  );
}
